import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Inter, Noto_Serif, Source_Code_Pro } from 'next/font/google';
import LayoutWrapper from './components/LayoutWrapper';
import './globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const notoSerif = Noto_Serif({
  variable: '--font-noto-serif',
  subsets: ['latin'],
});

const sourceCodePro = Source_Code_Pro({
  variable: '--font-source-code-pro',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${notoSerif.variable} ${sourceCodePro.variable} bg-neutral-100 font-sans text-neutral-950 antialiased transition-colors duration-300 dark:bg-neutral-800 dark:text-neutral-0`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <LayoutWrapper>{children}</LayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
